appname = APIS_MID_THE_HOUSEFIT
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:postgres@127.0.0.1:5432/THE_HOUSE_FITT_MID?sslmode=disable
